import type { Metadata } from "next";
import "./global.css"
import { Toaster } from "@/components/ui/sonner"
import {SessionProvider} from "next-auth/react"
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const  RootLayout = async({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) =>{
  const session = await auth();
  return (
    <html lang="en">
      <SessionProvider session={session}>
      <body
        className="font-bebas-neue"
      >
        {children}
        
        <Toaster/>
      </body>
      </SessionProvider>
    </html>
  );
};

export default RootLayout;
